SELECT rjpv.employee_id,
        rjpv.job_position_id,
        rjpv.organisation_id,
        rjpv.job_position_status,
        rjpv.employee_email,
        rjpv.employee_phone,
        rjpv.title,
        rjpv.employee_city,
        rjpv.country,
        rjpv.postcode,
        rjpv.medical_specialty,
        rjpv.medical_category,
        rjpv.professional_registration_number,
        rjpv.job_position_role,
        rjpv.job_position_role_description,
        rjpv.doctor_grade,
        rjpv.other_doctor_grade,
        rjpv.signed_off,
        rjpv.staff_type,
        rjpv.skip_onboarding,
        rjpv.compliance_status,
        rjpv.full_name,
        rjpv.tags,
        rjpv.create_timestamp
FROM {{ source('public', 'reporting_job_position_view') }} rjpv